[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
shmem = "0.2.0"
nix = { version = "0.29.0", features = ["mman", "fs"] }
jni = "0.21.1"
regex = "1.10.6"  # Add the jni crate to your dependencies

#[lib]
#crate-type = ["cdylib"]